// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgwexwahnjiycnbspdrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnd2V4d2FobmppeWNuYnNwZHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzgyODYsImV4cCI6MjA3NDU1NDI4Nn0.fNnW_rU817jeQOfr5AspxLf1ZFIMneB622Q0A4e5jMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});